WITH calendar AS (
  SELECT CAST(SEQ4() AS INT) AS i
  FROM TABLE(GENERATOR(ROWCOUNT => 40 * 365 * 24))
)
SELECT
  TIMESTAMPADD(
    HOUR,
    i,
    CAST('1990-01-01 00:00:00' AS TIMESTAMP_NTZ)
  ) AS full_datetime
FROM calendar
